### ISSUE TITLE
Could you add a "Login with Google" button that does not use the G+ icon

### ISSUE THREAD

**Issue by 1a2a3a4a** [MichalSzorad/react-social-login-buttons#1]
Hello thank you for your awesome buttons. Is it possible for you to add another button that follows this type of design which can be found here [Link to Google developers site](https://developers.google.com/identity/branding-guidelines)

**Comment by 1a2a3a4a** [comment]
Just read your readme and saw that you could create your own buttons and that you are still working on new ones.

**Comment by MichalSzorad** [comment]
Hello @1a2a3a4a and thank you for the feedback! 👍 

I have just released a new version and now you can pass children to SocialLoginButton.
You can see the example here  [How to create custom Google button](https://www.npmjs.com/package/react-social-login-buttons#create-your-own-button)

I am trying not to put a lot of images directly into the package because of its size. I am sorry to let you implement the button by yourself, but I hope the example will give you some idea how to write your own buttons.

If you have any questions, feel comfortable to write me a message :)

**Comment by seveibar** [comment]
I was confused to see the Google+ image as well, I came here to post an issue but then saw this. Many people have a google account, but only a fraction of those people use google plus.

Here's an example of the button on medium.

![selection_414](https://user-images.githubusercontent.com/1910070/37718646-91dc6bb6-2cf9-11e8-9588-80b43578ef99.png)

**Comment by seveibar** [comment]
@MichalSzorad I would be willing to PR a change to make the GoogleLoginButton use the new google style, and add a GooglePlusLoginButton if you're open to making the package size a bit bigger :)
